[
  {
    firstName: "Ana",
    lastName: "Johnson",
    email: "ana.demo@techtonic.com",
    specialty: "React",
    yearsExperience: 3,
  },
  {
    firstName: "Shambre",
    lastName: "Sanderson",
    email: "shambre.demo@techtonic.com",
    specialty: "Databases",
    yearsExperience: 3,
  },
  {
    firstName: "Sarah",
    lastName: "Callen",
    email: "sarah.demo@techtonic.com",
    specialty: "JavaScript",
    yearsExperience: 2,
  },
][
  ({
    firstName: "Grace",
    lastName: "Ford",
    username: "gf303",
    phoneNumber: "4795083477",
    groupNumber: 5,
    InstructorId: 1,
  },
  {
    firstName: "Brian",
    lastName: "Evantson",
    username: "brianthedev",
    phoneNumber: "3033773496",
    groupNumber: 5,
    InstructorId: 1,
  },
  {
    firstName: "Adina",
    lastName: "Brentson",
    username: "adinabinCO",
    phoneNumber: "3035705088",
    groupNumber: 4,
    InstructorId: 2,
  },
  {
    firstName: "Lindsay",
    lastName: "Chapson",
    username: "lcdev",
    phoneNumber: "3037833690",
    groupNumber: 2,
    InstructorId: 2,
  },
  {
    firstName: "Leo",
    lastName: "Andresen",
    username: "landresen",
    phoneNumber: "7206682365",
    groupNumber: 1,
    InstructorId: 3,
  },
  {
    firstName: "Aaron",
    lastName: "Lisey",
    username: "aaron303",
    phoneNumber: "3032195684",
    groupNumber: 1,
    InstructorId: 3,
  })
];
